// <auto-generated />
namespace FlightMode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class T11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(T11));
        
        string IMigrationMetadata.Id
        {
            get { return "202106282015009_T11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
