//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightMode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_item
    {
        public long item_id { get; set; }
        public Nullable<long> item_pid { get; set; }
        public string item_name { get; set; }
        public string item_sname { get; set; }
        public string item_unit { get; set; }
        public string item_bio_ref { get; set; }
        public string item_notes { get; set; }
        public string item_comments { get; set; }
        public string item_clinicaluse { get; set; }
        public string item_interpretation { get; set; }
        public Nullable<double> item_price { get; set; }
        public string item_created { get; set; }
        public string item_created_by { get; set; }
        public string item_updated { get; set; }
        public string item_updated_by { get; set; }
        public string item_status { get; set; }
    
        public virtual test_package test_package { get; set; }
    }
}
