//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightMode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianDetail
    {
        public long PhysicianId { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public string RegNo { get; set; }
        public string RegCouncil { get; set; }
        public string RegDate { get; set; }
        public string CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string UserId { get; set; }
        public Nullable<long> SPId { get; set; }
        public Nullable<long> EduId { get; set; }
        public Nullable<long> ExpId { get; set; }
    
        public virtual EduDetail EduDetail { get; set; }
        public virtual ExpDeatil ExpDeatil { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual User User { get; set; }
    }
}
