//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightMode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempReport
    {
        public long repid { get; set; }
        public string name { get; set; }
        public Nullable<long> labno { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string refby { get; set; }
        public string collected { get; set; }
        public string recieved { get; set; }
        public string reported { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<float> sgst { get; set; }
        public Nullable<float> cgst { get; set; }
        public Nullable<float> discount { get; set; }
        public Nullable<float> finalamount { get; set; }
        public string status { get; set; }
    }
}
