//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightMode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTest
    {
        public long testid { get; set; }
        public Nullable<long> reportid { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string unit { get; set; }
        public string bioreference { get; set; }
        public string remarks { get; set; }
    }
}
